### ISSUE TITLE
Sugesstion: Add a TL;DR section

### ISSUE THREAD

**Issue by vkbansal** [jlongster/electron-with-server-example#1]
First of all, **thanks** for the awesome example. It's really helpful.

Can a TL;DR section be added? It will be helpful for people who have already read through the entire readme file and can use it for quick reference\lookup

something like this:

| File                    | description         |
|----------------|-----------------|
[index.js](https://github.com/jlongster/electron-with-server-example/blob/master/index.js)| The main renderer process |
| [server-ipc.js](https://github.com/jlongster/electron-with-server-example/blob/master/server-ipc.js) | IPC handler for the server

**Comment by jlongster** [comment]
I don't have time to do this, but if you want to open a PR, I'd merge it!
