### ISSUE TITLE
local web server instead of IPC

### ISSUE THREAD

**Issue by sudhakar3697** [jlongster/electron-with-server-example#2]
I create a local web server and use http requests to communicate with UI.
Is it advisable? 
Thank you :)

**Comment by sudhakar3697** [comment]
@jlongster Could you give your suggestions?

**Comment by rchamberlin** [comment]
@sudhakar3697 The idea of this repo is to avoid using a web server for communication with the UI, but rather use IPC instead.

**Comment by jlongster** [comment]
Haven't been checking github - @sudhakar3697 you can do that, but it's slower and also is less secure. Anybody with network access can access HTTP, while only those with file access can access the socket. Theoretically a webpage could POST to http://localhost:8000 and they'd hit your server.
